"""Local CEO brief artifacts generated by NAWA OIP."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True)
class CEOBrief:
    """Short executive brief generated from one operational situation."""

    headline: str
    severity: str
    what_happened: str
    why_it_matters: str
    evidence_summary: list[dict[str, Any]]
    recommended_next_actions: list[str]
    confidence: str = "initial"

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly dictionary representation."""
        return asdict(self)
