"""Derived NAWA OIP artifacts produced from normalized records."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Any

from app.oip.models.ceo_brief import CEOBrief
from app.oip.models.operational_situation import OperationalSituation


@dataclass(frozen=True)
class OperationalMetric:
    """One normalized metric extracted or derived from an operational record."""

    metric_name: str
    value: Any | None
    date: date | None
    source_file: str
    source_row_number: int
    entity_type: str | None = None
    entity_reference: str | None = None
    sheet_name: str = ""
    report_shape: str = ""
    # Semantic claim provenance (Codex Round 2 Finding 3): metric_name is
    # already the canonical_field and value is already the normalized_value,
    # so only the original source header and its pre-normalization raw value
    # need to be added to make the claim fully traceable back to source.
    source_label: str | None = None
    raw_source_value: Any | None = None

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly dictionary representation."""
        payload = asdict(self)
        if self.date is not None:
            payload["date"] = self.date.isoformat()
        payload["source_file"] = Path(self.source_file).as_posix()
        return payload


@dataclass(frozen=True)
class OperationalEvent:
    """One local operational event draft generated by OIP."""

    event_type: str
    entity_type: str | None
    source_file: str
    date: date | None
    summary: str
    source_row_number: int
    entity_reference: str | None = None
    sheet_name: str = ""
    report_shape: str = ""
    # Populated only when the event maps to one direct source claim; a
    # whole-record summary event (e.g. poultry_daily_report) has none.
    source_label: str | None = None
    raw_source_value: Any | None = None

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly dictionary representation."""
        payload = asdict(self)
        if self.date is not None:
            payload["date"] = self.date.isoformat()
        payload["source_file"] = Path(self.source_file).as_posix()
        return payload


@dataclass(frozen=True)
class OperationalSignal:
    """One rule-based signal generated from local operational records."""

    signal_type: str
    severity: str
    message: str
    date: date | None
    source_file: str
    source_row_number: int
    entity_type: str | None = None
    entity_reference: str | None = None
    sheet_name: str = ""
    report_shape: str = ""
    # Populated with the source claim that directly triggered this signal
    # (e.g. daily_production_rate for production_below_standard), when there
    # is one direct triggering field.
    source_label: str | None = None
    raw_source_value: Any | None = None
    start_date: date | None = None
    end_date: date | None = None

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly dictionary representation."""
        payload = asdict(self)
        if self.date is not None:
            payload["date"] = self.date.isoformat()
        if self.start_date is not None:
            payload["start_date"] = self.start_date.isoformat()
        if self.end_date is not None:
            payload["end_date"] = self.end_date.isoformat()
        payload["source_file"] = Path(self.source_file).as_posix()
        return payload


@dataclass(frozen=True)
class PoultryDerivedArtifacts:
    """Container for all derived OIP artifacts from poultry records."""

    metrics: list[OperationalMetric]
    events: list[OperationalEvent]
    signals: list[OperationalSignal]
    situations: list[OperationalSituation]
    ceo_briefs: list[CEOBrief]
