"""Derived NAWA OIP artifacts produced from normalized records."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Any

from app.oip.models.ceo_brief import CEOBrief
from app.oip.models.operational_record import EpistemicOrigin, validate_epistemic_origin
from app.oip.models.operational_situation import OperationalSituation


@dataclass(frozen=True)
class OperationalMetric:
    """One normalized metric extracted or derived from an operational record.

    ``epistemic_origin`` is ``"observed"`` only when ``value`` is non-null
    AND ``source_label``/``raw_source_value`` are both resolvable - a
    non-null value alone is not sufficient proof of a source claim (a
    malformed or manually-constructed record could carry a value with no
    real provenance behind it). Every ``METRIC_FIELDS`` entry is, when
    fully source-backed, a direct unmodified copy of one record field,
    never a computation. A metric is still emitted when the record has no
    value/provenance for that field (existing missing-evidence detection
    depends on the object existing), but it is never classified OBSERVED in
    that case - it stays ``None`` (unresolved). See
    ``PoultryDerivationService._metric_epistemic_origin`` (Codex Round 1
    Finding 1 + Round 2 hardening, M4 Slice 1).
    """

    metric_name: str
    value: Any | None
    date: date | None
    source_file: str
    source_row_number: int
    entity_type: str | None = None
    entity_reference: str | None = None
    sheet_name: str = ""
    report_shape: str = ""
    # Semantic claim provenance (Codex Round 2 Finding 3): metric_name is
    # already the canonical_field and value is already the normalized_value,
    # so only the original source header and its pre-normalization raw value
    # need to be added to make the claim fully traceable back to source.
    source_label: str | None = None
    raw_source_value: Any | None = None
    epistemic_origin: EpistemicOrigin | None = None

    def __post_init__(self) -> None:
        validate_epistemic_origin(self.epistemic_origin)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly dictionary representation."""
        payload = asdict(self)
        if self.date is not None:
            payload["date"] = self.date.isoformat()
        payload["source_file"] = Path(self.source_file).as_posix()
        return payload


@dataclass(frozen=True)
class OperationalEvent:
    """One local operational event draft generated by OIP.

    ``epistemic_origin`` is ``"derived"`` for the whole-record
    ``poultry_daily_report`` summary event: it deterministically reformats
    multiple already-observed fields into one text summary via a fixed,
    auditable, non-AI rule (M4 Slice 1). It is deliberately not ``"observed"``
    because it does not correspond to one single source cell.
    """

    event_type: str
    entity_type: str | None
    source_file: str
    date: date | None
    summary: str
    source_row_number: int
    entity_reference: str | None = None
    sheet_name: str = ""
    report_shape: str = ""
    # Populated only when the event maps to one direct source claim; a
    # whole-record summary event (e.g. poultry_daily_report) has none.
    source_label: str | None = None
    raw_source_value: Any | None = None
    epistemic_origin: EpistemicOrigin | None = None

    def __post_init__(self) -> None:
        validate_epistemic_origin(self.epistemic_origin)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly dictionary representation."""
        payload = asdict(self)
        if self.date is not None:
            payload["date"] = self.date.isoformat()
        payload["source_file"] = Path(self.source_file).as_posix()
        return payload


@dataclass(frozen=True)
class OperationalSignal:
    """One rule-based signal generated from local operational records.

    ``epistemic_origin`` is ``"derived"`` for every signal type this service
    generates (M4 Slice 1): ``production_below_standard``/
    ``high_daily_mortality`` are deterministic threshold comparisons,
    ``data_quality_warning`` is a deterministic presence check, and
    ``production_declining_trend`` is a deterministic 3-window comparison -
    all auditable non-AI rules over observed values, with zero
    interpretation. None of PoultryDerivationService's signals are AI-based,
    so none are ever ``"inferred"`` - that classification is reserved for
    genuinely non-deterministic interpretation this service does not
    produce.
    """

    signal_type: str
    severity: str
    message: str
    date: date | None
    source_file: str
    source_row_number: int
    entity_type: str | None = None
    entity_reference: str | None = None
    sheet_name: str = ""
    report_shape: str = ""
    # Populated with the source claim that directly triggered this signal
    # (e.g. daily_production_rate for production_below_standard), when there
    # is one direct triggering field.
    source_label: str | None = None
    raw_source_value: Any | None = None
    epistemic_origin: EpistemicOrigin | None = None
    start_date: date | None = None
    end_date: date | None = None

    def __post_init__(self) -> None:
        validate_epistemic_origin(self.epistemic_origin)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly dictionary representation."""
        payload = asdict(self)
        if self.date is not None:
            payload["date"] = self.date.isoformat()
        if self.start_date is not None:
            payload["start_date"] = self.start_date.isoformat()
        if self.end_date is not None:
            payload["end_date"] = self.end_date.isoformat()
        payload["source_file"] = Path(self.source_file).as_posix()
        return payload


@dataclass(frozen=True)
class PoultryDerivedArtifacts:
    """Container for all derived OIP artifacts from poultry records."""

    metrics: list[OperationalMetric]
    events: list[OperationalEvent]
    signals: list[OperationalSignal]
    situations: list[OperationalSituation]
    ceo_briefs: list[CEOBrief]
